### ISSUE TITLE
v1.0 To-Do List

### ISSUE THREAD

**Issue by sera1mu** [sera1mu/deno-mecab#1]
- [x] Parse (形態素解析) 16d41b568c07ec45af35df5d1821fd4bc5dffd8b
- [x] Chasen (形態素解析 - Chasen互換) baaa53002e6b0ad4ec33f9e0b5de6b1cac795b8c
- [x] Simple (形態素解析 - 簡潔なやつ) 1742c19974eb7c2b8efaef5f7dfff9cd3ce89169
- [x] Wakati (分かち書き) a10043b2d5d2ed129429f579c580b371f2f6251c
- [x] Yomi (読み付与) 5a6c6d725b03ca10af757ef1e27ead668982c499
- [x] Dump (出力ダンプ) d0527c53bd9192468574d1db54eaa7f10ce8b62f
- [x] テスト記述 c22108d0591eb123d1abdef056ff70df69dac458
- [x] Codecovでテストカバレッジを収集する c96567c7c7bf2fbe3a0cc41ea4efefe5456f9e3a
- [x] READMEを書く31866383311e1bebadbc66fbda21cafc4cd11d14
- [x] **v1.0.0 リリース**
- [x] deno.land/x へのパブリッシュ
